# Generated by Django 3.2.4 on 2021-09-18 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('DOB', models.DateTimeField()),
                ('sex', models.CharField(max_length=10)),
                ('blood_pressure', models.CharField(max_length=10)),
                ('risk_factor', models.FloatField()),
            ],
        ),
    ]
